### ISSUE TITLE
Victor broke the pip install. Please fix.

### ISSUE THREAD

**Issue by TrystanScottLambert** [TrystanScottLambert/pyFoF#33]
thanks. 
trying poetry.

**Comment by BrutishGuy** [comment]
Current project structure doesn't allow standard python build, as pypi expects a very specific folder layout which is difficult to extend.
Switching to use Poetry for building and publishing the package due its extensibility and versatility. Additionally it was on the roadmap for the repository in any case, so this is merely forcing us to do it earlier.

Will post updates here once the issue is resolved.

**Comment by BrutishGuy** [comment]
I have created a new release, v1.0.7, published to PyPI and tested via Test PyPI.

- Migrated to Poetry
- Fixed bad imports arising from PyPI package environment

@TrystanScottLambert give it a try on your end, example commands 
```python
import pyFoF
from pyFoF.fof import ClassicFoF
from pyFoF.metrics import redshift_davies_bouldin_score
from pyFoF.survey import Survey
from pyFoF.fof import Trial
from pyFoF.experiment import Experiment
from pyFoF.report import GroupReport
import pyFoF.utils as utils

```

**Comment by TrystanScottLambert** [comment]
@BrutishGuy 

All looking good. Tried using python 3.11, 3.10.9, and have user who tried 3.10.4. Working perfect across all of those. Good job :)
